### ISSUE TITLE
is pix2vox give a real world volume object file

### ISSUE THREAD

**Issue by vigneshgig** [hzxie/Pix2Vox#1]

**Comment by hzxie** [comment]
What do you mean?
You mean the volumes for Pix3D?

**Comment by vigneshgig** [comment]
yes, the volume of the final 3d output

**Comment by hzxie** [comment]
The 3D volumes for Pix3D can be generated from CAD models (i.e., `.obj` files) with [binvox](https://www.patrickmin.com/binvox/).
