### ISSUE TITLE
TypeError:not all arguments converted during string formatting

### ISSUE THREAD

**Issue by rjb1322** [hzxie/Pix2Vox#10]
Hello, Mr. hzxie.After I modified the file path of the datasets according to README,I started training or testing datasets of ShapeNet.But both reported the same error:"TypeError:not all arguments converted during string formatting".I don't know if it's a path problem or anything else?

**Comment by hzxie** [comment]
There MUST be something wrong with your path in the `config.py`.
Could you please provide your path in the `config.py`?

**Comment by ikhblo** [comment]
Hello, Mr. hzxie.I also have the same problem, But I don’t know if there is a problem with the path. Can you help check it out.thank you very much.
![path](https://user-images.githubusercontent.com/67190477/117529768-19919700-b00c-11eb-8ee3-b563a8ea50f0.png)

**Comment by hzxie** [comment]
There are two placeholders in the path. But you ONLY have one.

```
__C.DATASETS.SHAPENET.RENDERING_PATH        = '/home/hzxie/Datasets/ShapeNet/ShapeNetRendering/%s/%s/rendering/%02d.png'
__C.DATASETS.SHAPENET.VOXEL_PATH            = '/home/hzxie/Datasets/ShapeNet/ShapeNetVox32/%s/%s/model.binvox'
```

**Comment by ikhblo** [comment]
Thank you very much for the answer.But I still ran into a problem., When the picture path is %02d.jpg at the end, the program can run. When the picture path is %s.jpg at the end,program can't run.The problem is image files  not exists.

**Comment by hzxie** [comment]
I think you should read the documentation of the `placeholders` (e.g. %d, %s, %02d) of print.
