### ISSUE TITLE
how to get the same catogary but different objects in the same batch

### ISSUE THREAD

**Issue by dengchengxifrank** [hzxie/Pix2Vox#100]
Dear xie,thanks for your wonderful work.About the code,I wonder how to get the same catogary but different objects in the same batch.For example,the input is  torch.Size([batch_size, n_views, img_c, img_h, img_w]),but I wonder as for the data from the different batch,is it from the same catogray?And how can I change the code to get the result as torch.Size([batch_size, n_category, n_views, img_c, img_h, img_w])? thanks a lot!

**Comment by hzxie** [comment]
Just modify the code below.

https://github.com/hzxie/Pix2Vox/blob/5f75fbd71b4b8d9145bef320530c5e1803646254/utils/data_loaders.py#L31-L89
