### ISSUE TITLE
Process is killed.

### ISSUE THREAD

**Issue by karansspk** [hzxie/Pix2Vox#103]
[DEBUG] 2023-10-26 15:42:05.539573 Parameters in Encoder: 7772480.
[DEBUG] 2023-10-26 15:42:05.539690 Parameters in Decoder: 71583064.
[DEBUG] 2023-10-26 15:42:05.539721 Parameters in Refiner: 34880352.
[DEBUG] 2023-10-26 15:42:05.539812 Parameters in Merger: 8571.
[INFO/Process-1] child process calling self.run()
[INFO/Process-2] child process calling self.run()
[INFO/Process-3] child process calling self.run()
[INFO/Process-4] child process calling self.run()
[INFO/Process-3] created temp directory /tmp/pymp-ot00qigy
[INFO/Process-1] created temp directory /tmp/pymp-s_yx84dk
[INFO/Process-2] created temp directory /tmp/pymp-y7981tt_
[INFO/Process-4] created temp directory /tmp/pymp-jd_434ho
[INFO] 2023-10-26 15:42:25.584945 [Epoch 1/250][Batch 1/478] BatchTime = 19.683 (s) DataTime = 0.793 (s) EDLoss = 9.9270 RLoss = 9.7593
Killed

After this the process stops.

**Comment by hzxie** [comment]
Please check whether your RAM is full.
