### ISSUE TITLE
Pre trained weights

### ISSUE THREAD

**Issue by 100060970** [hzxie/Pix2Vox#104]
Hello,
The link for the Pix2VoxA and Pix2VoxF pre-trained weights does not work. 
The pre-trained models on ShapeNet are available as follows: the two links do not work. Kindly help me with thus.
Regards

**Comment by hzxie** [comment]
The link works well for me.

<img width="1582" alt="Screenshot 2023-11-02 at 8 51 29 PM" src="https://github.com/hzxie/Pix2Vox/assets/1730504/0f9ca45a-1d45-4623-b94c-522d1c6da977">

**Comment by buxuangjiehun** [comment]
wait a minute and it work for me
