### ISSUE TITLE
ShapeNet dataset

### ISSUE THREAD

**Issue by 100060970** [hzxie/Pix2Vox#105]
Hello,
The links to download shapenet dataset does not work.
ShapeNet rendering images: http://cvgl.stanford.edu/data2/ShapeNetRendering.tgz
ShapeNet voxelized models: http://cvgl.stanford.edu/data2/ShapeNetVox32.tgz.
The links do not work.
Kindly guide me so that I can access them.
Regards

**Comment by hzxie** [comment]
Maybe you can find the two files from
- http://ftp.cs.stanford.edu/cs/cvgl/ShapeNetRendering.tgz
- http://ftp.cs.stanford.edu/cs/cvgl/ShapeNetVox32.tgz
