### ISSUE TITLE
Versions update

### ISSUE THREAD

**Issue by Solomonraj017** [hzxie/Pix2Vox#106]
Hello Team, I am trying to implement this code, but I am unable to view images.
Could you kindly provide me the version numbers of the required packages or libraries from requirements.txt file that you have used.
It would be of great help.

Thanks in advance.

**Comment by hzxie** [comment]
Please provide specific error logs.

**Comment by swapnilGhosh007** [comment]
Hello, after executing runner.py, the model is being trained but it is using CPU instead of GPU. I am using RTX 4090 which is CUDA enabled. I created a conda environment and installed the requirements.txt. Using python 3.11.5. Can anyone please help me.

Thanks in advance.
