### ISSUE TITLE
Model training is using CPU instead of GPU

### ISSUE THREAD

**Issue by swapnilGhosh007** [hzxie/Pix2Vox#107]
![Capture](https://github.com/hzxie/Pix2Vox/assets/66404911/6fe28f23-0769-4be6-ac79-2fd8f2ba5a37)
![Capture](https://github.com/hzxie/Pix2Vox/assets/66404911/6416716b-3c56-4cf4-b9d6-c1ea78619dc5)
Hello, after executing runner.py, the model is being trained but it is using CPU instead of GPU. I am using RTX 4090 which is CUDA enabled. I created a conda environment and installed the requirements.txt. Using python 3.9.18 Can anyone please help me.

Thanks in advance.

**Comment by hzxie** [comment]
Please check your environment again. The problem is not related to Pix2Vox.
I guess the output of the following Python code is `False`.

```
import torch
print(torch.cuda.is_available())
```
