### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Solomonraj017** [hzxie/Pix2Vox#109]
I hope you are doing great, I am trying to implement this code but I have certain questions, would you kindly guide me through the following please.
1. After running runner.py, I get the output folder with checkpoints, images (with empty white image as 'voxels-001.png') and logs, could you guide me why is the image complete white and is it supposed to be 3d reconstructed output image?

2. In config.py file, the changes you mentioned in the path are as below
 __C.DATASETS.PASCAL3D.VOXEL_PATH            = '/path/to/Datasets/PASCAL3D/CAD/%s/%02d.binvox
but there is no .binvox file in PASCAL3D/CAD  but it is  '.off' file in the original dataset
and also in 
__C.DATASETS.PIX3D.VOXEL_PATH               = '/path/to/Datasets/Pix3D/model/%s/%s/%s.binvox'
there is no .binvox in Pix3D/model file either but instead there are.obj and .mat files.

I tried with all the combinations but I think my code isn't picking up the datasets correctly. Could you kindly let me know what changes should be made exactly.

3. in Config.py file , could you please tell me what is line no. 61 means, '__C.DIR.RANDOM_BG_PATH = '/home/hzxie/Datasets/SUN2012/JPEGImages' and what are the changes that can be made here if at all anything is needed.

4. And in file, Pix3d.json in datasets, the taxonomy file contains only chair but not any other object, but we are considering only aeroplane to run this code, so could you please elaborate on this.

Thanks for understanding.

**Comment by hzxie** [comment]
1. The images in the training dataset are with white background. If you feed the network with clutter-background images, there will be a large domain gap. You can use [SAM](https://github.com/facebookresearch/segment-anything) to segment the object first.
2. The .binvox file should be generated from the .off file. Please refer to this script: https://github.com/hzxie/Pix2Vox/blob/master/utils/binvox_converter.py
3. Benefiting from SAM, I think pretrained with SUN2012 images is no longer needed.
4. As far as I recall, Pix3D contains approximately 2800 chairs, but only a limited number of objects for other categories. Training on Pix3D for other categories appears to be infeasible.

**Comment by Solomonraj017** [comment]
Thank you so much for the clarity in your answers.

**Comment by xujunjiejerry** [comment]
Could you please advise on how to address the issue of slow training speed, and where should the pre-trained model be downloaded from? The link in the readme does not provide the download address. Looking forward to your reply

<img width="1692" height="975" alt="Image" src="https://github.com/user-attachments/assets/08cc643e-4878-44dc-a980-501ae858839f" />

<img width="1947" height="795" alt="Image" src="https://github.com/user-attachments/assets/5dec4974-1d32-483e-9a52-5b8006310e59" />

**Comment by hzxie** [comment]
<img width="892" height="489" alt="Image" src="https://github.com/user-attachments/assets/c4739260-5723-4826-b002-acd1059e0672" />

@xujunjiejerry 
For pretrained weights, please check your Internet connection to `www.gstatic.com`.

For the slow training speed, please check whether you are using CPU.
