### ISSUE TITLE
Pix2vox output form

### ISSUE THREAD

**Issue by ChauncyFr** [hzxie/Pix2Vox#11]
Does anyone know how to save the output as a 3D model?

**Comment by hzxie** [comment]
You can simply use the following code:

```
pred_volume = ...

with open('/tmp/model_id.binvox', 'wb') as f:
    vox = binvox_rw.Voxels(pred_volume.cpu().numpy(), (32,) * 3, (0,) * 3, 1, 'xyz')
    vox.write(f)
```

**Comment by ChauncyFr** [comment]
> You can simply use the following code:
> 
> ```
> pred_volume = ...
> 
> with open('/tmp/model_id.binvox', 'wb') as f:
>     vox = binvox_rw.Voxels(pred_volume.cpu().numpy(), (32,) * 3, (0,) * 3, 1, 'xyz')
>     vox.write(f)
> ```

Thanks

**Comment by ChauncyFr** [comment]
> You can simply use the following code:
> 
> ```
> pred_volume = ...
> 
> with open('/tmp/model_id.binvox', 'wb') as f:
>     vox = binvox_rw.Voxels(pred_volume.cpu().numpy(), (32,) * 3, (0,) * 3, 1, 'xyz')
>     vox.write(f)
> ```

如何将生成的结果保存为 “.obj” 格式呢？

**Comment by hzxie** [comment]
@ChauncyFr 
You cannot save it to `.obj` directly.

**Comment by ChauncyFr** [comment]
> @ChauncyFr
> You cannot save it to `.obj` directly.

I borrowed the method of saving 3D R2N2 as obj. I tried it and it was ok, but the final saved obj file was a bit large. Or do you know how to convert from ".binvox" to ".obj" format

**Comment by aashishbohra10** [comment]
> You can simply use the following code:
> 
> ```
> pred_volume = ...
> 
> with open('/tmp/%s.binvox' % model_id, 'wb') as f:
>     vox = binvox_rw.Voxels(pred_volume.cpu().numpy(), (32,) * 3, (0,) * 3, 1, 'xyz')
>     vox.write(f)
> ```



hey .. I am not getting where to add this code referred by you in #11?
and also tell what will happen by this code?

**Comment by aashishbohra10** [comment]
Traceback (most recent call last):
  File "/workspace/storage/Pix2Vox/runner.py", line 93, in <module>
    main()
  File "/workspace/storage/Pix2Vox/runner.py", line 77, in main
    test_net(cfg)
  File "/workspace/storage/Pix2Vox/core/test.py", line 211, in test_net
    with open('/tmp/%s.binvox' % model_id, 'wb') as f:
NameError: name 'model_id' is not defined



What is model_id..??

**Comment by hzxie** [comment]
@aashishbohra10 
Please use your brain, OK?

**Comment by Mayank-git** [comment]
> You can simply use the following code:
> 
> ```
> pred_volume = ...
> 
> with open('/tmp/%s.binvox' % model_id, 'wb') as f:
>     vox = binvox_rw.Voxels(pred_volume.cpu().numpy(), (32,) * 3, (0,) * 3, 1, 'xyz')
>     vox.write(f)
> ```

What should be there in pred_volume if i want output of all the available classes in ShapeNet dataset?

**Comment by hzxie** [comment]
@Mayank-git 
Consider using `np.squeeze()`.

**Comment by Mayank-git** [comment]
> @Mayank-git
> Consider using `np.squeeze()`.

Thanks, its is working but I am facing a new problem now, all the generated binvox files are of 4KB only. Can you please guide me for the same?
![Screen Shot 2020-05-10 at 5 25 20 PM](https://user-images.githubusercontent.com/29223911/81498551-2ab5a400-92e3-11ea-8964-acbf8d4b1d75.png)

**Comment by hzxie** [comment]
@Mayank-git 
Try to convert np.array to np.bool before saving.

**Comment by Acumen7** [comment]
> > [@ChauncyFr](https://github.com/ChauncyFr)
> > You cannot save it to `.obj` directly.
> 
> I borrowed the method of saving 3D R2N2 as obj. I tried it and it was ok, but the final saved obj file was a bit large. Or do you know how to convert from ".binvox" to ".obj" format

Sorry to bother. I tried to save generated_volume as .obj but failed, Could you be kind to show the code for that ?
