### ISSUE TITLE
About URNet

### ISSUE THREAD

**Issue by Sand-Glass** [hzxie/Pix2Vox#110]
Great work, I'd like to reproduce, just ran into some confusion.

1. Regarding the SUN3D dataset, I don’t know how to download it. I found many folders on the official website https://sun3d.cs.princeton.edu/, which one should I download?
![image](https://github.com/hzxie/Pix2Vox/assets/96899552/30f84557-6b93-43ef-bdc5-c438574164aa)

2.Which dataset is the Pix2Vox++ used in URNet trained on (SUN3D and the final actual demonstration)?

Besides, I don’t know if you have any plans to open source it. If you can, it would be greatly appreciated.

**Comment by hzxie** [comment]
What is URNet?

**Comment by hzxie** [comment]
SUNCG is no longer available due to the law case between Planner 5D and Princeton.
See also: 
- https://gritdaily.com/facebook-princeton-ai-computer-vision-lawsuit-dismissed-for-now/
- https://github.com/facebookresearch/House3D/issues/57

**Comment by Sand-Glass** [comment]
> What is URNet?

URNet is the scene reconstruction network mentioned in Chapter 5 of your paper ([3D Scene and Object Reconstruction from Multiple Sources and Viewpoints](https://www.infinitescript.com/publications/xie2021threedim.pdf)).
I'm trying to reproduce it, but I don't know which data set the Pix2Vox++ you used was trained on.
I'm thinking it's in Thing3D-Chairs-RFC? Or just go directly to ShapeNet-Chairs.

**Comment by hzxie** [comment]
In which paper did I mention SUN3D?
Sorry, the work was done more than a half-decade ago, I cannot remember the details.

**Comment by Sand-Glass** [comment]
Hahaha, it is mentioned on page 85 of this paper([3D Scene and Object Reconstruction from Multiple Sources and Viewpoints](https://www.infinitescript.com/publications/xie2021threedim.pdf)).
![image](https://github.com/hzxie/Pix2Vox/assets/96899552/317576b5-4178-46f8-b1aa-e1dde5805d1a)
**What should I do to reproduce them?**

**Comment by hzxie** [comment]
Please refer to https://sun3d.cs.princeton.edu/
