### ISSUE TITLE
Is it possible to change the output dimensions from (32, 32, 32) to (64, 64, 64) or (128, 128, 128)  ?

### ISSUE THREAD

**Issue by WillLLS** [hzxie/Pix2Vox#111]
Hello guys, thank you for you work, it is really impressive !

Is it possible to modify the architecture to have an output of size (128, 128, 128) or (64,64,64) instead of (32, 32, 32) ? If yes, do you recommand something to do ? I saw in the config file __C.CONST.N_VOX = 32 but it looks to be hard coded in the model definitions, so I"m wondering how to do it ?

Thanks a lot for your time !

**Comment by hzxie** [comment]
Refer to #89
