### ISSUE TITLE
pix3d models are .obj not .binvox

### ISSUE THREAD

**Issue by shayansep** [hzxie/Pix2Vox#114]
hello,

is the code writtent in a way, to train on all the pix3d, pascal3d and shapenet all at once ?

you know that the pix3d 3d-models are in .obj format, but inside the config.py, it asks for binovax formats:
__C.DATASETS.PIX3D.VOXEL_PATH               = '/path/to/Datasets/Pix3D/model/%s/%s/%s.binvox'

do i have to turn them into binovax ? ( which will be veryyy time consuming ) or its fine like that? ( to keep them as .obj ) and do i have to change the address to :
__C.DATASETS.PIX3D.VOXEL_PATH               = '/path/to/Datasets/Pix3D/model/%s/%s/%s.obj'  ??

**and also, you didnt put the link to the specific pascal3d dataset that we have to use, because config.py has also lines for pascal3d paths.**
and again im asking if the train.py code written in a way to train on all those dataset all at once ?

please guide me
thank you for your attention

**Comment by hzxie** [comment]
Please refer to the answers in the following issues.

1. #25
2. #4
