### ISSUE TITLE
Deployment issues due to py & lib versions

### ISSUE THREAD

**Issue by Wakeelfahmed** [hzxie/Pix2Vox#115]
In your requirements file, u haven't mentioned the specific version of lib. I request to plz mention the specific version of lib and python version u used, so deployment is possible easily.

I am currently using python 3.10.14.

**Run:**
!python3 /kaggle/working/Pix2Vox/runner.py --test --weights=/kaggle/input/pix2vox-a-shapenet/Pix2Vox-A-ShapeNet.pth

**Console:**
Traceback (most recent call last):
  File "/kaggle/working/Pix2Vox/runner.py", line 20, in <module>
    from core.train import train_net
  File "/kaggle/working/Pix2Vox/core/train.py", line 12, in <module>
    import utils.data_loaders
  File "/kaggle/working/Pix2Vox/utils/data_loaders.py", line 18, in <module>
    import utils.binvox_rw
  File "/kaggle/working/Pix2Vox/utils/binvox_rw.py", line 206, in <module>
    def dense_to_sparse(voxel_data, dtype=np.int):
  File "/opt/conda/lib/python3.10/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?

**Comment by hzxie** [comment]
After reading the stack trace, the solution is quite clear. You can try one of the following:

1. Downgrade to numpy < 1.20
2. Change line 206 of the file "/kaggle/working/Pix2Vox/utils/binvox_rw.py": `dense_to_sparse(voxel_data, dtype=np.int)` to `dense_to_sparse(voxel_data, dtype=np.int32)`
