### ISSUE TITLE
reconstruct another category other than aeroplane

### ISSUE THREAD

**Issue by Tharooo** [hzxie/Pix2Vox#117]
Thank you for your effort in this paper, i want to know how can i modify the code to be able to reconstruct another category other than aeroplane. i when i run runner.py i only have aeroplane reconstructed. for ex: what should i do to reconstruct car or table category? (i am using shapenet for multiview)

aeroplane reconstructed
![resulto](https://github.com/user-attachments/assets/cf7041cd-535a-4ef6-b4c7-fd7d594932de)

**Comment by hzxie** [comment]
Just give a car/table image as input.

**Comment by Tharooo** [comment]
where i can change this in the code?

**Comment by hzxie** [comment]
https://github.com/hzxie/Pix2Vox/blob/69e2579f9baab90eac1ec0a24c184d010e9a0fde/core/test.py#L103

You can add an IF statement conditioned on the specific category ID.

**Comment by Tharooo** [comment]
thank you!

**Comment by PrithviRaj037** [comment]
Hey,

Could you help me to run this model?
