### ISSUE TITLE
Pix3D dataloader error

### ISSUE THREAD

**Issue by liupgd** [hzxie/Pix2Vox#17]
In the code, the pix3d dataset is regared as '.binvox' format files. But, in fact, there are only '.obj' files and '.mat' files.  The Pix3dDataset is wrong.

**Comment by hzxie** [comment]
You need to generate .binvox files from .obj by yourself.

**Comment by ChauncyFr** [comment]
> You need to generate .binvox files from .obj by yourself.

Thanks，I did it yesterday.
Thanks， again！

**Comment by Hans1984** [comment]
Hey, I meet the same problem, could you please tell me how to generate .binvox from .obj? Thanks a lot

**Comment by hzxie** [comment]
@Hans1984 
Please consider using this tool.
https://www.patrickmin.com/binvox/

**Comment by Hans1984** [comment]
Thanks
