### ISSUE TITLE
Questions about the two fully connected layers in Pix2Vox?

### ISSUE THREAD

**Issue by ChauncyFr** [hzxie/Pix2Vox#18]
I have a question about the two fully two layers in this network. These two fully connected layers occupy a lot of parameters. Can you ask, what is the role of these two layers?

![](https://tva1.sinaimg.cn/large/006tNbRwly1g9m5ob6sp4j313u0k4abc.jpg)

**Comment by hzxie** [comment]
FC can aggregate global information of the 3D volume.
Removing FC layers may degenerate reconstruction quality.
