### ISSUE TITLE
Why use ELU？

### ISSUE THREAD

**Issue by bluestyle97** [hzxie/Pix2Vox#2]
Hi, thanks for your wonderful work! But I'm just wondering that why would you use ELU activations in the encoder instead of simply using ReLU? Can you explain that? Thanks a lot!

**Comment by hzxie** [comment]
An interesting problem.
I tried ReLU, but the performance would be a little bit lower than the network using ELU.

**Comment by hzxie** [comment]
@bluestyle97 
**UPDATE:**
Actually, the experiment I mentioned above was done last year. And there have some changes in the network architecture. 
Therefore, I'm not sure whether ReLU can outperform ELU now.
I suggest you conduct this experiment again.
Good luck.
