### ISSUE TITLE
Question about the context-aware fusion module

### ISSUE THREAD

**Issue by ChauncyFr** [hzxie/Pix2Vox#23]
When I was looking at the source code, I was not sure where the "context-aware fusion module" mentioned in the article was implemented in the code? Is this a few lines of code to achieve this function? Looking forward to your answer, thank you!

![](https://tva1.sinaimg.cn/large/006tNbRwly1gaodvj82ufj314s0fu759.jpg)

**Comment by hzxie** [comment]
merger.py corresponds to the context-aware fusion module.
