### ISSUE TITLE
Output unclear

### ISSUE THREAD

**Issue by 3Dyou-Manasa** [hzxie/Pix2Vox#24]
Hi great resource, thank you.

Unclear on 4 things though:
1. where is the output being stored, I checked the 'Output' folder but I only see logs there, nothing else!
2. in what format is output being generated? Is it .binvox files?
3. How do we test the model on new/unseen data?
4. Also, I see that ShapeNetRendering dataset consists of multiview images per each object; isn't this code for single-view image to 3D?

**Comment by hzxie** [comment]
1. The output of 3D volumes is not stored by default. If you want to save them, please refer to issue  #11.
2. It depends on the code. The output format of the example code in #11 is `.binvox`.
3. You need to generate a new rendering of unseen categories of ShapeNet with 3D software (e.g., Blender).
4. I cannot understand this question. Could you explain it?

**Comment by 3Dyou-Manasa** [comment]
I will refer to #11 thank you
4. This code repo outputs 3D models from single image view/rendering or needs multiple image renderings?

**Comment by hzxie** [comment]
Both settings are OK.
