### ISSUE TITLE
Unable to load weights  without CUDA

### ISSUE THREAD

**Issue by vjayd** [hzxie/Pix2Vox#3]
Error in loading state_dict for encoder while trying to load the pretrained weights

**Comment by hzxie** [comment]
Can you provide more logs?
I cannot reproduce your problem.

**Comment by vjayd** [comment]
Missing key(s) in state_dict: "vgg.0.weight", "vgg.0.bias", "vgg.1.weight", "vgg.1.bias", "vgg.1.running_mean", "vgg.1.running_var", "vgg.3.weight", "vgg.3.bias", "vgg.4.weight", "vgg.4.bias", "vgg.4.running_mean", "vgg.4.running_var", "vgg.7.weight", "vgg.7.bias", "vgg.8.weight", "vgg.8.bias", "vgg.8.running_mean", "vgg.8.running_var", "vgg.10.weight", "vgg.10.bias", "vgg.11.weight", "vgg.11.bias", "vgg.11.running_mean", "vgg.11.running_var", "vgg.14.weight", "vgg.14.bias", "vgg.15.weight", "vgg.15.bias", "vgg.15.running_mean", "vgg.15.running_var", "vgg.17.weight", "vgg.17.bias", "vgg.18.weight", "vgg.18.bias", "vgg.18.running_mean", "vgg.18.running_var", "vgg.20.weight", "vgg.20.bias", "vgg.21.weight", "vgg.21.bias", "vgg.21.running_mean", "vgg.21.running_var", "vgg.24.weight", "vgg.24.bias", "vgg.25.weight", "vgg.25.bias", "vgg.25.running_mean", "vgg.25.running_var", "layer1.0.weight", "layer1.0.bias", "layer1.1.weight", "layer1.1.bias", "layer1.1.running_mean", "layer1.1.running_var", "layer2.0.weight", "layer2.0.bias", "layer2.1.weight", "layer2.1.bias", "layer2.1.running_mean", "layer2.1.running_var", "layer3.0.weight", "layer3.0.bias", "layer3.1.weight", "layer3.1.bias", "layer3.1.running_mean", "layer3.1.running_var".                                                                                                  Unexpected key(s) in state_dict: "module.vgg.0.weight", "module.vgg.0.bias", "module.vgg.1.weight", "module.vgg.1.bias", "module.vgg.1.running_mean", "module.vgg.1.running_var", "module.vgg.1.num_batches_tracked", "module.vgg.3.weight", "module.vgg.3.bias", "module.vgg.4.weight", "module.vgg.4.bias", "module.vgg.4.running_mean", "module.vgg.4.running_var", "module.vgg.4.num_batches_tracked", "module.vgg.7.weight", "module.vgg.7.bias", "module.vgg.8.weight", "module.vgg.8.bias", "module.vgg.8.running_mean", "module.vgg.8.running_var", "module.vgg.8.num_batches_tracked", "module.vgg.10.weight", "module.vgg.10.bias", "module.vgg.11.weight", "module.vgg.11.bias", "module.vgg.11.running_mean", "module.vgg.11.running_var", "module.vgg.11.num_batches_tracked", "module.vgg.14.weight", "module.vgg.14.bias", "module.vgg.15.weight", "module.vgg.15.bias", "module.vgg.15.running_mean", "module.vgg.15.running_var", "module.vgg.15.num_batches_tracked", "module.vgg.17.weight", "module.vgg.17.bias", "module.vgg.18.weight", "module.vgg.18.bias", "module.vgg.18.running_mean", "module.vgg.18.running_var", "module.vgg.18.num_batches_tracked", "module.vgg.20.weight", "module.vgg.20.bias", "module.vgg.21.weight", "module.vgg.21.bias", "module.vgg.21.running_mean", "module.vgg.21.running_var", "module.vgg.21.num_batches_tracked", "module.vgg.24.weight", "module.vgg.24.bias", "module.vgg.25.weight", "module.vgg.25.bias", "module.vgg.25.running_mean", "module.vgg.25.running_var", "module.vgg.25.num_batches_tracked", "module.layer1.0.weight", "module.layer1.0.bias", "module.layer1.1.weight", "module.layer1.1.bias", "module.layer1.1.running_mean", "module.layer1.1.running_var", "module.layer1.1.num_batches_tracked", "module.layer2.0.weight", "module.layer2.0.bias", "module.layer2.1.weight", "module.layer2.1.bias", "module.layer2.1.running_mean", "module.layer2.1.running_var", "module.layer2.1.num_batches_tracked", "module.layer3.0.weight", "module.layer3.0.bias", "module.layer3.1.weight", "module.layer3.1.bias", "module.layer3.1.running_mean", "module.layer3.1.running_var", "module.layer3.1.num_batches_tracked".                                                       [INFO/MainProcess] process shutting down

**Comment by vjayd** [comment]
I am loading Pix2Vox A model with its pretrained weights

**Comment by hzxie** [comment]
What's your PyTorch version?
Because the following statements is not working on your machine:

```
encoder = torch.nn.DataParallel(encoder).cuda()
decoder = torch.nn.DataParallel(decoder).cuda()
refiner = torch.nn.DataParallel(refiner).cuda()
merger = torch.nn.DataParallel(merger).cuda()
```

**Comment by vjayd** [comment]
I am not using cuda

**Comment by vjayd** [comment]
Pytorch version 1.0.1

**Comment by hzxie** [comment]
emmmm.
There's a simple solution for you. Please use the following statement to create a new pretrained model:

```
import torch
ckpt = torch.load('/path/to/ckpt.pth')
new_ckpt = {}
for k1 in ['encoder_state_dict', 'decoder_state_dict', 'refiner_state_dict', 'merger_state_dict']:
  new_ckpt[k1] = {}
  for k2 in ckpt[k1].keys():
      new_ckpt[k1.replace('module.', '')][k2] = ckpt[k1][k2]

torch.save(new_ckpt, '/path/to/new/ckpt.pth')
```

**Comment by vjayd** [comment]
Tried running the file but now I ma getting this error 


epoch_idx = checkpoint['epoch_idx']                                                                                                                                 KeyError: 'epoch_idx'

**Comment by hzxie** [comment]
@vjayd 
There are two solutions to this problem:
1. Create the `epoch_idx` in the pretrained model.
2. Remove this statement.

**Comment by vjayd** [comment]
Alright, Is there any way to test the model with specific set of images? Lets say I have 13 viewpoints and  want to see the binvox file of those particular images. Rather then downloading the entire shapenet dataset.

**Comment by hzxie** [comment]
You need to change the IO of the project.
