### ISSUE TITLE
Where to add this code ?

### ISSUE THREAD

**Issue by aashishbohra10** [hzxie/Pix2Vox#31]
you can simply use the following code:
pred_volume = ...

with open('/tmp/%s.binvox' % model_id, 'wb') as f:
    vox = binvox_rw.Voxels(pred_volume.cpu().numpy(), (32,) * 3, (0,) * 3, 1, 'xyz')
    vox.write(f)

hey .. I am not getting where to add this code referred by you in #11?
and also tell what will happen by this code?

**Comment by hzxie** [comment]
You can add this code in test.py.

**Comment by hzxie** [comment]
This code saves the prediction results to a binvox file.
