### ISSUE TITLE
What comes in pred_volume

### ISSUE THREAD

**Issue by aashishbohra10** [hzxie/Pix2Vox#32]
As per the reference you mentioned i.e. #11 . If I want the output of all the classes in shapenet dataset then What exactly needs to come in pred_volume?

**Comment by hzxie** [comment]
With the given code, you can output the predicted 3D volumes for **EVERY** object in the testing set.
SO, WHAT'S YOUR PROBLEM?
I CANNOT UNDERSTAND WHY YOU KEEP ASKING SUCH STUPID QUESTIONS!!

**Comment by hzxie** [comment]
With the given code, you can output the predicted 3D volumes for EVERY object in the testing set.
SO, WHAT'S YOUR PROBLEM?
