### ISSUE TITLE
How to visualize the reconstruction results?

### ISSUE THREAD

**Issue by fangyuansama** [hzxie/Pix2Vox#33]
I wonder how can I visualize the reconstruction results like you do in the original paper.
Examples are shown in the picture.
![result](https://user-images.githubusercontent.com/47934195/82137855-2d1d7e00-984e-11ea-9e99-394208606eb2.png)

**Comment by hzxie** [comment]
Consider using https://github.com/davidstutz/bpy-visualization-utils

**Comment by saisai1002** [comment]
> I wonder how can I visualize the reconstruction results like you do in the original paper.
> Examples are shown in the picture.
> ![result](https://user-images.githubusercontent.com/47934195/82137855-2d1d7e00-984e-11ea-9e99-394208606eb2.png)
 Have you solved the problem ？

**Comment by hzxie** [comment]
> Consider using https://github.com/davidstutz/bpy-visualization-utils

@saisai1002 Open you eyes!
