### ISSUE TITLE
ValueError:cannot reshape array of size 110207 into shape (32,32,32)

### ISSUE THREAD

**Issue by rjb1322** [hzxie/Pix2Vox#36]
Hello! I have output a binvox file as #11,but that file doesn't open properly,the error display as"ValueError:cannot reshape array of size 110207 into shape (32,32,32)"
    I was wondering if there was anything wrong with saving the data?
    Looking forward to your reply!Thank you.

**Comment by hzxie** [comment]
Please provide the full logs with stacktrace.

**Comment by rjb1322** [comment]
1.I first converted the data type to bool output
 pred_volume = generated_volume.squeeze()
            pred = pred_volume.cpu().numpy()
            pred.dtype = 'bool'
            with open('%s.binvox' % taxonomy_id, 'wb') as f:
                vox = utils.binvox_rw.Voxels(pred, (32,) * 3, (0,) * 3, 1, 'xyz')
                vox.write(f)

2.Use binvox_rw.pu to view data
(base) E:\study\3Dproject\binvox-rw-py-public>python
Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import binvox_rw
>>> with open('02691156.binvox', 'rb') as f:
...      model = binvox_rw.read_as_3d_array(f)
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "E:\study\3Dproject\binvox-rw-py-public\binvox_rw.py", line 144, in read_as_3d_array
    data = data.reshape(dims)
ValueError: cannot reshape array of size 110207 into shape (32,32,32)

The program can see the normal voxel file,but  I generated this binvox file can't open

**Comment by rjb1322** [comment]
1.I first converted the data type to bool output
pred_volume = generated_volume.squeeze()
pred = pred_volume.cpu().numpy()
pred.dtype = 'bool'
with open('%s.binvox' % taxonomy_id, 'wb') as f:
vox = utils.binvox_rw.Voxels(pred, (32,) * 3, (0,) * 3, 1, 'xyz')
vox.write(f)

2.Use binvox_rw.py to view data
(base) E:\study\3Dproject\binvox-rw-py-public>python
Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.

            import binvox_rw
            with open('02691156.binvox', 'rb') as f:
            ... model = binvox_rw.read_as_3d_array(f)
            ...
            Traceback (most recent call last):
            File "", line 2, in
            File "E:\study\3Dproject\binvox-rw-py-public\binvox_rw.py", line 144, in read_as_3d_array
            data = data.reshape(dims)
            ValueError: cannot reshape array of size 110207 into shape (32,32,32)

The program can see the normal voxel file,but I generated this binvox file can't open

**Comment by hzxie** [comment]
It seems there is nothing wrong with your code.
Could you tell me the shape of `pred`?
