### ISSUE TITLE
How to calculate the size or volume of the reconstruction result?

### ISSUE THREAD

**Issue by HuangHuim** [hzxie/Pix2Vox#38]
If the distance between camera and target is known, is it possible to estimate the size of the 3D reconstruction result obtained by your method? If yes, how to calculate?

**Comment by hzxie** [comment]
Theoretically speaking, you can.
However, all objects in ShapeNet have the same size. For example, the size of an airplane is the same as a chair.

**Comment by HuangHuim** [comment]
How does it work in theory? If all objects have the same size, how to calculate its real size? From pixel size?

**Comment by hzxie** [comment]
You can not do that with ShapeNet.
