### ISSUE TITLE
Pascal3d dataset

### ISSUE THREAD

**Issue by RitikaAg** [hzxie/Pix2Vox#4]
Is the Pascal3d dataset to be downloaded as well ,since no link has been provided for downloading it,but a path to it has been set in the code.

**Comment by hzxie** [comment]
Pascal 3D has been deprecated because of the overlap between the training and testing samples.
You can download Pascal 3D from [here](ftp://cs.stanford.edu/cs/cvgl/PASCAL3D+_release1.1.zip).

**Comment by RitikaAg** [comment]
@hzxie okay thanks

**Comment by xujunjiejerry** [comment]
I would like to ask what the training samples and test samples are respectively. Could you please provide a more detailed and clear explanation? Looking forward to your reply.
