### ISSUE TITLE
Why only use the first image to evaluate the model ?

### ISSUE THREAD

**Issue by RanFeng** [hzxie/Pix2Vox#45]
https://github.com/hzxie/Pix2Vox/blob/f1b82823e79d4afeedddfadb3da0940bcf1c536d/utils/data_loaders.py#L66
Dear @hzxie , why only use the first image to evaluate the model rather than all 24 images? What was the consideration? Thank you !

**Comment by hzxie** [comment]
It does not stand for the first image. Actually, it is the first **n** images.

**Comment by RanFeng** [comment]
Thank you for your reply! so, when we evaluate model with single view, that is, n = 1 , why use only first image rather than all 24 images? what was the consideration?

**Comment by hzxie** [comment]
You can change the number of views in `config.py`. It is possible to use 24 images during testing.

**Comment by hzxie** [comment]
You have said that for **single-view**.
Single-view means n == 1, doesn't it?

**Comment by RanFeng** [comment]
Yes, I mean, why only use **first** image rather than **other** image or **last** image?

**Comment by hzxie** [comment]
It follows the settings of 3D-R2N2.

**Comment by RanFeng** [comment]
Your results in paper for single view is 0.661, It is got from only first image or all images respectively evaluated in **single view**?

**Comment by hzxie** [comment]
Only the first image.

**Comment by RanFeng** [comment]
OK, I got it , Thank you!
