### ISSUE TITLE
Things3D

### ISSUE THREAD

**Issue by Medoalmasry** [hzxie/Pix2Vox#46]
In the paper [Pix2Vox++: Multi-scale Context-aware 3D Object Reconstruction from Single and Multiple Images]
it says

> We construct a large-scale dataset, named Things3D,
> containing 1.68M images of 280K objects collected
> from over 39K indoor scenarios.

Is that dataset publicly available? If yes, would you be kind enough and provide a link?

**Comment by hzxie** [comment]
The Things3D will be publicly available when the patent application is done.
