### ISSUE TITLE
Generalizability Issues

### ISSUE THREAD

**Issue by 4ri4Slr** [hzxie/Pix2Vox#47]
Hi,

I tried testing the pretrained model on a number of CAD models from the ABC dataset, but the network fails to recover the shapes, even when 5 views are used. I rendered the 2D images using Blender. I wonder if it is the method of rendering that is causing the problem, or the model just cannot generalize to unseen classes. I should also mention that the code worked fine on the customized ShapeNet dataset provided in the repo. Any thoughts? I have attached the model, reconstruction, and the rendered views down below. 
Thanks

![gtv](https://user-images.githubusercontent.com/57267379/90990086-56d3f880-e553-11ea-8953-51ddf905a14f.jpg)
![gv](https://user-images.githubusercontent.com/57267379/90990087-576c8f00-e553-11ea-9b93-09b8619ef820.jpg)
[04.zip](https://github.com/hzxie/Pix2Vox/files/5115125/04.zip)

**Comment by hzxie** [comment]
At least, you need to fine-tune on the ABC dataset.
In our paper, we tested our model (pretrained on the ShapeNet dataset) on the unseen classes of the ShapeNet dataset. The gap between the classes should be much smaller.
