### ISSUE TITLE
NotImplementedError: Axes3D currently only supports the aspect argument 'auto'. You passed in 'equal'.

### ISSUE THREAD

**Issue by ahmedshingaly** [hzxie/Pix2Vox#48]
Greetings, 
I faced below error while running` runner.py` file, any suggestions will be appreciated. 

[INFO] 2020-09-07 11:14:58.773195 [Epoch 1/250][Batch 473/478] BatchTime = 0.609 (s) DataTime = 0.000 (s) EDLoss = 1.5209 RLoss = 1.4220
[INFO] 2020-09-07 11:14:59.339636 [Epoch 1/250][Batch 474/478] BatchTime = 0.566 (s) DataTime = 0.001 (s) EDLoss = 1.5411 RLoss = 1.4908
[INFO] 2020-09-07 11:14:59.899355 [Epoch 1/250][Batch 475/478] BatchTime = 0.560 (s) DataTime = 0.000 (s) EDLoss = 1.5617 RLoss = 1.4801
[INFO] 2020-09-07 11:15:03.457158 [Epoch 1/250][Batch 476/478] BatchTime = 3.558 (s) DataTime = 2.985 (s) EDLoss = 1.4925 RLoss = 1.4052
[INFO] 2020-09-07 11:15:04.028943 [Epoch 1/250][Batch 477/478] BatchTime = 0.572 (s) DataTime = 0.000 (s) EDLoss = 1.5314 RLoss = 1.4357
[INFO] 2020-09-07 11:15:04.586913 [Epoch 1/250][Batch 478/478] BatchTime = 0.558 (s) DataTime = 0.001 (s) EDLoss = 1.4898 RLoss = 1.3886
[INFO/Process-2] process shutting down
[INFO/Process-1] process shutting down
[INFO/Process-3] process shutting down
[INFO/Process-2] process exiting with exitcode 0
[INFO/Process-4] process shutting down
[INFO/Process-1] process exiting with exitcode 0
[INFO/Process-3] process exiting with exitcode 0
[INFO/Process-4] process exiting with exitcode 0
[INFO] 2020-09-07 11:15:04.620620 Epoch [1/250] EpochTime = 713.621 (s) EDLoss = 3.1987 RLoss = 2.5285
[INFO/Process-5] child process calling self.run()
[INFO/Process-5] created temp directory /tmp/pymp-mf7icpus
[INFO/Process-5] process shutting down
[INFO/Process-5] process exiting with exitcode 0
Traceback (most recent call last):
  File "runner.py", line 93, in <module>
    main()
  File "runner.py", line 74, in main
    train_net(cfg)
  File "/home/ahmed/Documents/3DAI/Pix2Vox_hzxie/Pix2Vox/core/train.py", line 264, in train_net
    iou = test_net(cfg, epoch_idx + 1, output_dir, val_data_loader, val_writer, encoder, decoder, refiner, merger)
  File "/home/ahmed/Documents/3DAI/Pix2Vox_hzxie/Pix2Vox/core/test.py", line 151, in test_net
    epoch_idx)
  File "/home/ahmed/Documents/3DAI/Pix2Vox_hzxie/Pix2Vox/utils/binvox_visualization.py", line 19, in get_volume_views
    ax.set_aspect('equal')
  File "/home/ahmed/anaconda3/envs/py37/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 324, in set_aspect
    "Axes3D currently only supports the aspect argument "
NotImplementedError: Axes3D currently only supports the aspect argument 'auto'. You passed in 'equal'.
[INFO/MainProcess] process shutting down

when debugging it says 
The reason for a NotImplementedError being raised is indeed that aspect is not implemented for 3D axes. This was added deliberately in #13474 to tell people about the fact that this feature does not (yet) exist.
is there a workaround? 
thank you in advance

**Comment by ahmedshingaly** [comment]
here is my conda list 

conda list 
# packages in environment at /home/ahmed/anaconda3/envs/py37:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
absl-py                   0.10.0                   pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               20.1.0           py37h7b6447c_1  
argparse                  1.4.0                    pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
astroid                   2.4.2                    pypi_0    pypi
attrs                     20.1.0                     py_0  
autograd                  1.3                      pypi_0    pypi
backcall                  0.2.0                      py_0  
batchgenerators           0.19.3                   pypi_0    pypi
black                     19.10b0                  pypi_0    pypi
blas                      1.0                         mkl  
bleach                    3.1.5                      py_0  
ca-certificates           2020.7.22                     0  
certifi                   2020.6.20                py37_0  
cffi                      1.14.2           py37he30daa8_0  
chardet                   3.0.4                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
cloudpickle               1.6.0                    pypi_0    pypi
configparser              5.0.0                    pypi_0    pypi
cudatoolkit               10.1.243             h6bb024c_0  
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.21                  pypi_0    pypi
dbus                      1.13.16              hb2f20db_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
delira                    0.6.0                    pypi_0    pypi
detectron2                0.2.1                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
easydict                  1.9                      pypi_0    pypi
entrypoints               0.3                      py37_0  
expat                     2.2.9                he6710b0_2  
flake8                    3.8.3                    pypi_0    pypi
flake8-bugbear            20.1.4                   pypi_0    pypi
flake8-comprehensions     3.2.3                    pypi_0    pypi
fontconfig                2.13.0               h9420a91_0  
freetype                  2.10.2               h5ab3b9f_0  
freetype-py               2.2.0                    pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
fvcore                    0.1.1.post20200716            py_0    conda-forge
gast                      0.4.0                    pypi_0    pypi
gitdb                     4.0.5                    pypi_0    pypi
gitpython                 3.1.7                    pypi_0    pypi
glib                      2.65.0               h3eb4bd4_0  
google-pasta              0.2.0                    pypi_0    pypi
gql                       0.2.0                    pypi_0    pypi
graphql-core              1.1                      pypi_0    pypi
grpcio                    1.31.0                   pypi_0    pypi
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb31296c_0  
h5py                      2.10.0                   pypi_0    pypi
icu                       58.2                 he6710b0_3  
idna                      2.10                     pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
imageio-ffmpeg            0.4.2                    pypi_0    pypi
importlib-metadata        1.7.0                    py37_0  
importlib_metadata        1.7.0                         0  
intel-openmp              2020.2                      254  
ipykernel                 5.3.4            py37h5ca1d4c_0  
ipython                   7.17.0           py37h5ca1d4c_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.5.1                      py_0  
isort                     5.4.2                    pypi_0    pypi
jedi                      0.17.2                   py37_0  
jinja2                    2.11.2                     py_0  
joblib                    0.16.0                   pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
jsonpatch                 1.26                     pypi_0    pypi
jsonpointer               2.0                      pypi_0    pypi
jsonschema                3.2.0                    py37_1  
jupyter                   1.0.0                    py37_7  
jupyter_client            6.1.6                      py_0  
jupyter_console           6.1.0                      py_0  
jupyter_core              4.6.3                    py37_0  
kaggle                    1.5.6                    pypi_0    pypi
keras                     2.4.3                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.2.0                    pypi_0    pypi
lazy-object-proxy         1.4.3                    pypi_0    pypi
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libgpuarray               0.7.6                h14c3975_0  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h7b6447c_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               he19cac6_1  
linecache2                1.0.0                    pypi_0    pypi
lz4-c                     1.9.2                he6710b0_1  
mako                      1.1.3                      py_0  
markdown                  3.2.2                    pypi_0    pypi
markupsafe                1.1.1            py37h14c3975_1  
mathutils                 2.81.2                   pypi_0    pypi
matplotlib                3.3.1                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
meshrcnn                  1.0                       dev_0    <develop>
mistune                   0.8.4           py37h14c3975_1001  
mkl                       2020.2                      256  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.1.0            py37h23d657b_0  
mkl_random                1.1.1            py37h0573a6f_0  
mock                      4.0.2                    pypi_0    pypi
moviepy                   1.0.2                    pypi_0    pypi
nbconvert                 5.6.1                    py37_1  
nbformat                  5.0.7                      py_0  
ncurses                   6.2                  he6710b0_1  
nested-lookup             0.2.21                   pypi_0    pypi
networkx                  2.3                      pypi_0    pypi
ninja                     1.10.0.post1             pypi_0    pypi
notebook                  6.1.1                    py37_0  
numpy                     1.19.1                   pypi_0    pypi
nvidia-ml-py3             7.352.0                  pypi_0    pypi
olefile                   0.46                     py37_0  
opencv-python             4.4.0.42                 pypi_0    pypi
openssl                   1.1.1g               h7b6447c_0  
packaging                 20.4                       py_0  
pandas                    1.1.1                    pypi_0    pypi
pandoc                    2.10.1                        0  
pandocfilters             1.4.2                    py37_1  
parso                     0.7.0                      py_0  
pathspec                  0.8.0                    pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
pcre                      8.44                 he6710b0_0  
pexpect                   4.8.0                    py37_1  
pickleshare               0.7.5                 py37_1001  
pillow                    7.2.0            py37hb39fc2d_0  
pip                       20.2.2                   py37_0  
portalocker               1.7.0            py37hc8dfbb8_0    conda-forge
proglog                   0.1.9                    pypi_0    pypi
prometheus_client         0.8.0                      py_0  
promise                   2.3                      pypi_0    pypi
prompt-toolkit            3.0.5                      py_0  
prompt_toolkit            3.0.5                         0  
protobuf                  3.13.0                   pypi_0    pypi
psutil                    5.7.2                    pypi_0    pypi
ptyprocess                0.6.0                    py37_0  
pycocotools               2.0.1                    pypi_0    pypi
pycodestyle               2.6.0                    pypi_0    pypi
pycparser                 2.20                       py_2  
pycuda                    2019.1.2                 pypi_0    pypi
pydot                     1.4.1                    pypi_0    pypi
pyflakes                  2.2.0                    pypi_0    pypi
pygments                  2.6.1                      py_0  
pygpu                     0.7.6            py37heb32a55_0  
pylint                    2.6.0                    pypi_0    pypi
pyparsing                 2.4.7                      py_0  
pyqt                      5.9.2            py37h05f1152_2  
pyrsistent                0.16.0           py37h7b6447c_0  
python                    3.7.7                hcff3b4d_5  
python-dateutil           2.8.1                      py_0  
python-slugify            4.0.1                    pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytools                   2020.4                   pypi_0    pypi
pytorch3d                 0.2.0                    pypi_0    pypi
pytz                      2020.1                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pyyaml                    5.3.1            py37h8f50634_0    conda-forge
pyzmq                     19.0.1           py37he6710b0_1  
qt                        5.9.7                h5867ecd_1  
qtconsole                 4.7.6                      py_0  
qtpy                      1.9.0                      py_0  
readline                  8.0                  h7b6447c_0  
regex                     2020.7.14                pypi_0    pypi
requests                  2.24.0                   pypi_0    pypi
scikit-image              0.17.2                   pypi_0    pypi
scikit-learn              0.23.2                   pypi_0    pypi
scipy                     1.5.2                    pypi_0    pypi
send2trash                1.5.0                    py37_0  
sentry-sdk                0.17.0                   pypi_0    pypi
setuptools                49.6.0                   py37_0  
shapedata                 0.2.0                    pypi_0    pypi
shapenet                  0.1.0                    pypi_0    pypi
shortuuid                 1.0.1                    pypi_0    pypi
sip                       4.19.8           py37hf484d3e_0  
six                       1.15.0                     py_0  
sklearn                   0.0                      pypi_0    pypi
smmap                     3.0.4                    pypi_0    pypi
sqlite                    3.33.0               h62c20be_0  
subprocess32              3.5.4                    pypi_0    pypi
tabulate                  0.8.7              pyh9f0ad1d_0    conda-forge
tensorboard               1.15.0                   pypi_0    pypi
tensorboardx              2.1                      pypi_0    pypi
tensorflow                1.14.0                   pypi_0    pypi
tensorflow-estimator      1.14.0                   pypi_0    pypi
tensorflow-gpu            1.14.0                   pypi_0    pypi
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.8.3                    py37_0  
testpath                  0.4.4                      py_0  
text-unidecode            1.3                      pypi_0    pypi
theano                    0.8.0                    pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
tifffile                  2020.8.25                pypi_0    pypi
tk                        8.6.10               hbc83047_0  
toml                      0.10.1                   pypi_0    pypi
torch                     1.6.0                    pypi_0    pypi
torchfile                 0.1.0                    pypi_0    pypi
torchvision               0.7.0                    pypi_0    pypi
tornado                   6.0.4            py37h7b6447c_1  
tqdm                      4.48.2             pyh9f0ad1d_0    conda-forge
traceback2                1.4.0                    pypi_0    pypi
traitlets                 4.3.3                    py37_0  
transforms3d              0.3.1                    pypi_0    pypi
typed-ast                 1.4.1                    pypi_0    pypi
unittest2                 1.1.0                    pypi_0    pypi
urllib3                   1.24.3                   pypi_0    pypi
visdom                    0.1.8.9                  pypi_0    pypi
vispy                     0.6.4                    pypi_0    pypi
wandb                     0.9.5                    pypi_0    pypi
watchdog                  0.10.3                   pypi_0    pypi
watermark                 2.0.2                    pypi_0    pypi
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py37_1  
websocket-client          0.57.0                   pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.35.1                     py_0  
widgetsnbextension        3.5.1                    py37_0  
wrapt                     1.12.1                   pypi_0    pypi
xz                        5.2.5                h7b6447c_0  
yacs                      0.1.6                      py_0    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zeromq                    4.3.2                he6710b0_2  
zipp                      3.1.0                      py_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0

**Comment by hzxie** [comment]
Try to downgrade matplotlib to 3.0.3.
See also #13 and #35.

**Comment by ahmedshingaly** [comment]
thanks you, that worked I faced another problem in image.py file,  but downgrading tensorboardX to 1.2.0 solved that problem.
now I am running the runner.py and hopefully it works as expected.  
thanks alot for sharing the code and fast support
