### ISSUE TITLE
how to  checkout to Pix2Vox++-F branch

### ISSUE THREAD

**Issue by langyakun** [hzxie/Pix2Vox#49]
hello~
I'd like to test Pix2Vox++-F and use "git checkout -b Pix2Vox++-F origin/Pix2Vox++-F" in git, but there is something wrong happend: _fatal: 'origin/Pix2Vox++-F' is not a commit and a branch 'Pix2Vox++-F' cannot be created from it_
I tried "git pull" but it didn't work, could you give me some other advice? thanks.

**Comment by hzxie** [comment]
The source code for Pix2Vox++ is availble at https://gitlab.com/hzxie/Pix2Vox.

**Comment by langyakun** [comment]
> The source code for Pix2Vox++ is availble at https://gitlab.com/hzxie/Pix2Vox.

sorry, maybe i did't say clearly.
 I run the command python runner.py --test --weights=Pix2Vox++-F-ShapeNet.pth and had issue like this:
![error1](https://user-images.githubusercontent.com/48083310/92550898-47f97f80-f28f-11ea-8e0c-fd9cb7d8a1e7.jpg)
so, refer to the issue#6, i checkout to the Pix2Vox++-F branch before load the model and have this question:
![error](https://user-images.githubusercontent.com/48083310/92550932-5f386d00-f28f-11ea-8546-ab9c8d2aa78f.jpg)

**Comment by hzxie** [comment]
@langyakun 
Please note that the source code is available at **GITLAB** instead of **GITHUB**.

**Comment by langyakun** [comment]
@hzxie thanks for your reply. another question:
I changed dataset path to my own path in config.py, but Idon't know whether  "C.DIR.RANDOM_BG_PATH= '/home/hzxie/Datasets/SUN2012/JPEGImages" should be changed, i have error like this:

_**_Traceback (most recent call last):
  File "runner.py", line 93, in <module>
    main()
  File "runner.py", line 74, in main
    train_net(cfg)
  File "F:\code\prePix2Vox\Pix2Vox\core\train.py", line 144, in train_net
    train_writer = SummaryWriter(os.path.join(log_dir, 'train'))
  File "D:\tf\anaconda\anaconda_gpu\envs\tensorflow-gpu\lib\site-packages\tensorboardX\writer.py", line 275, in __init__
    self._get_file_writer()
  File "D:\tf\anaconda\anaconda_gpu\envs\tensorflow-gpu\lib\site-packages\tensorboardX\writer.py", line 327, in _get_file_writer
    self.kwargs)
  File "D:\tf\anaconda\anaconda_gpu\envs\tensorflow-gpu\lib\site-packages\tensorboardX\writer.py", line 95, in __init__
    logdir, max_queue, flush_secs, filename_suffix)
  File "D:\tf\anaconda\anaconda_gpu\envs\tensorflow-gpu\lib\site-packages\tensorboardX\event_file_writer.py", line 104, in __init__
    directory_check(self._logdir)
  File "D:\tf\anaconda\anaconda_gpu\envs\tensorflow-gpu\lib\site-packages\tensorboardX\record_writer.py", line 51, in directory_check
    os.makedirs(path)
  File "D:\tf\anaconda\anaconda_gpu\envs\tensorflow-gpu\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "D:\tf\anaconda\anaconda_gpu\envs\tensorflow-gpu\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: './output\\logs\\2020-09-09T21:10:50.335259'
[INFO/MainProcess] process shutting down_**_

 This is my config file, i only use ShapeNet dataset.
 Dataset Config:
__C.DATASETS.SHAPENET = edict()
__C.DATASETS.SHAPENET.TAXONOMY_FILE_PATH = './datasets/ShapeNet.json'
__C.DATASETS.SHAPENET.RENDERING_PATH= 'F:/code/database/ShapeNet/ShapeNetRendering/%s/%s/rendering/%02d.png'
__C.DATASETS.SHAPENET.VOXEL_PATH = 'F:/code/database/ShapeNet/ShapeNetVox32/%s/%s/model.binvox'

 Directories:

__C.DIR                                     = edict()
__C.DIR.OUT_PATH                            = './output'
__C.DIR.RANDOM_BG_PATH                      = '/home/hzxie/Datasets/SUN2012/JPEGImages'

**Comment by hzxie** [comment]
C.DIR.RANDOM_BG_PATH is optional.

You need to update 

https://github.com/hzxie/Pix2Vox/blob/f1b82823e79d4afeedddfadb3da0940bcf1c536d/core/train.py#L157

to

```
output_dir = os.path.join(cfg.DIR.OUT_PATH, '%s', dt.now().isoformat()).replace(':', '-')
```

to solve the following  issue:

```
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: './output\logs\2020-09-09T21:10:50.335259'
```
