### ISSUE TITLE
程序测试出现“Please specify the file path of checkpoint”问题

### ISSUE THREAD

**Issue by SeanYangtj** [hzxie/Pix2Vox#5]
您好，您好像只提供了Pix3D和ShapeNet的链接，PASCAL3D的链接好像没有提供，其次是SUN2012 DB的链接是不是也需要修改，所以出现了这个问题？

正在下载数据进行测试.....

**Comment by hzxie** [comment]
You don't need to update the path of Pascal3D+ and SUN 2012.
Please double check the file path of checkpoint .

**Comment by SeanYangtj** [comment]
Thank you! I have solved this problem. Although I have tried a lot, but it's also a stupid question......

**Comment by SeanYangtj** [comment]
如果使用CPU，除了增加`map_location='cpu'`以外，可能还会出现`Error(s) in loading state_dict for Encoder:`错误
需要使用`encoder.load_state_dict({k.replace('module.',''):v for k,v in checkpoint['encoder_state_dict'].items()})`把key里面的`module.`替换掉......
用GPU+CUAD应该不会出现..CPU在我电脑上运行是会出现这个问题
运行环境：Intel Core i7, MacOS, Python3.7.4, Pytorch1.1.0.post2
正在研读学长的论文，非常敬仰
<img width="805" alt="image" src="https://user-images.githubusercontent.com/32950943/62716405-b9378500-ba34-11e9-9659-0487da85c864.png">

**Comment by hzxie** [comment]
If you are using CPU. Please refer #3.
If you need help, please provide more error logs.
