### ISSUE TITLE
Output is only console?

### ISSUE THREAD

**Issue by lui-shex** [hzxie/Pix2Vox#52]
When I run this command, output file is empty.
`python3 runner.py --test --weights=/path/to/pretrained/model.pth`

[INFO/Process-1] process shutting down
[INFO/Process-1] process exiting with exitcode 0
============================ TEST RESULTS ============================
Taxonomy        #Sample Baseline        t=0.20  t=0.30  t=0.40  t=0.50
aeroplane       810     0.5130          0.6665  0.6842  0.6903  0.6889
bench           364     0.4210          0.6024  0.6157  0.6203  0.6151
cabinet         315     0.7160          0.7895  0.7924  0.7919  0.7847
car             1501    0.7980          0.8476  0.8548  0.8568  0.8533
chair           1357    0.4660          0.5638  0.5666  0.5631  0.5493
display         220     0.4680          0.5347  0.5373  0.5336  0.5188
lamp            465     0.3810          0.4481  0.4430  0.4340  0.4170
speaker         325     0.6620          0.7166  0.7144  0.7090  0.6939
rifle           475     0.5440          0.6042  0.6148  0.6147  0.6050
sofa            635     0.6280          0.7061  0.7092  0.7080  0.6984
table           1703    0.5130          0.5977  0.6006  0.5983  0.5857
telephone       211     0.6610          0.7696  0.7764  0.7792  0.7783
watercraft      389     0.5130          0.5898  0.5946  0.5902  0.5779
Overall                                 0.6555  0.6610  0.6600  0.6506

[INFO/MainProcess] process shutting down

How can I fix it?

Thanks!

**Comment by hzxie** [comment]
Please refer to other issues, such as #51.
