### ISSUE TITLE
Please specify the file path of checkpoint.

### ISSUE THREAD

**Issue by coffeesha** [hzxie/Pix2Vox#56]
When I am running the command: python runner.py --test --weights=/Desktop/3D_object/pmodels/Pix2Vox++-A-ShapeNet.pth 

following error is shown

Use config:
{'CONST': {'BATCH_SIZE': 64,
           'CROP_IMG_H': 128,
           'CROP_IMG_W': 128,
           'DEVICE': '0',
           'IMG_H': 224,
           'IMG_W': 224,
           'N_VIEWS_RENDERING': 1,
           'N_VOX': 32,
           'RNG_SEED': 0,
           'WEIGHTS': '/Desktop/3D_object/pmodels/Pix2Vox++-A-ShapeNet.pth'},
 'DATASET': {'MEAN': [0.5, 0.5, 0.5],
             'STD': [0.5, 0.5, 0.5],
             'TEST_DATASET': 'ShapeNet',
             'TRAIN_DATASET': 'ShapeNet'},
 'DATASETS': {'PASCAL3D': {'ANNOTATION_PATH': '/F:/Data/PASCAL3D/Annotations/%s_imagenet/%s.mat',
                           'RENDERING_PATH': '/F:/Data/PASCAL3D/Images/%s_imagenet/%s.JPEG',
                           'TAXONOMY_FILE_PATH': './datasets/Pascal3D.json',
                           'VOXEL_PATH': '/F:/Data/PASCAL3D/CAD/%s/%02d.binvox'},
              'PIX3D': {'ANNOTATION_PATH': '/F:/Data/Pix3D/pix3d.json',
                        'RENDERING_PATH': '/F:/Data/Pix3D/img/%s/%s.%s',
                        'TAXONOMY_FILE_PATH': './datasets/Pix3D.json',
                        'VOXEL_PATH': '/F:/Data/Pix3D/model/%s/%s/%s.binvox'},
              'SHAPENET': {'RENDERING_PATH': '/F:/Data/ShapeNet/ShapeNetRendering/%s/%s/rendering/%02d.png',
                           'TAXONOMY_FILE_PATH': './datasets/ShapeNet.json',
                           'VOXEL_PATH': '/F:/Data/ShapeNet/ShapeNetVox32/%s/%s/model.binvox'}},
 'DIR': {'OUT_PATH': './output',
         'RANDOM_BG_PATH': '/home/hzxie/Datasets/SUN2012/JPEGImages'},
 'NETWORK': {'LEAKY_VALUE': 0.2,
             'TCONV_USE_BIAS': False,
             'USE_MERGER': True,
             'USE_REFINER': True},
 'TEST': {'RANDOM_BG_COLOR_RANGE': [[240, 240], [240, 240], [240, 240]],
          'VOXEL_THRESH': [0.2, 0.3, 0.4, 0.5]},
 'TRAIN': {'BETAS': [0.9, 0.999],
           'BRIGHTNESS': 0.4,
           'CONTRAST': 0.4,
           'DECODER_LEARNING_RATE': 0.001,
           'DECODER_LR_MILESTONES': [150],
           'ENCODER_LEARNING_RATE': 0.001,
           'ENCODER_LR_MILESTONES': [150],
           'EPOCH_START_USE_MERGER': 0,
           'EPOCH_START_USE_REFINER': 0,
           'GAMMA': 0.5,
           'MERGER_LEARNING_RATE': 0.0001,
           'MERGER_LR_MILESTONES': [150],
           'MOMENTUM': 0.9,
           'NOISE_STD': 0.1,
           'NUM_EPOCHES': 250,
           'NUM_WORKER': 4,
           'POLICY': 'adam',
           'RANDOM_BG_COLOR_RANGE': [[225, 255], [225, 255], [225, 255]],
           'REFINER_LEARNING_RATE': 0.001,
           'REFINER_LR_MILESTONES': [150],
           'RESUME_TRAIN': False,
           'SATURATION': 0.4,
           'SAVE_FREQ': 10,
           'UPDATE_N_VIEWS_RENDERING': False}}
[FATAL] 2020-11-27 23:30:42.416623 Please specify the file path of checkpoint.
[INFO/MainProcess] process shutting down

**Comment by hzxie** [comment]
@coffeesha 

Obviously, the path to the pretrained model is incorrect.

If not, please provide the output of the following:

```
ls -l /Desktop/3D_object/pmodels/Pix2Vox++-A-ShapeNet.pth
```
