### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Encoder: size mismatch for layer2.0.weight: copying a param with shape torch.Size([256, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).

### ISSUE THREAD

**Issue by coffeesha** [hzxie/Pix2Vox#57]
Greetings,
I am getting this error when I loaded pretrained weights
It will be very helpful if someone gives some insights on how to solve this issue

Traceback (most recent call last):
  File "runner.py", line 97, in <module>
    main()
  File "runner.py", line 81, in main
    test3_net(cfg)
  File "E:\1_Srividya\ENGINEERING\1_Final_year_proj\3D_object\core\test3.py", line 94, in test3_net
    encoder.load_state_dict(new_ckpt['encoder_state_dict'],strict = False)
  File "C:\Users\Srividya\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Encoder:
        size mismatch for layer2.0.weight: copying a param with shape torch.Size([256, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
        size mismatch for layer2.0.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for layer2.1.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for layer2.1.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for layer2.1.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for layer2.1.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for layer3.0.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 512, 1, 1]).
[INFO/MainProcess] process shutting down

**Comment by hzxie** [comment]
Please give me the output of following:

```
git status
git branch
```

It seems that you tried to load the Pix2Vox-F weights to Pix2Vox-A.
