### ISSUE TITLE
Pytorch Shape Issue

### ISSUE THREAD

**Issue by ShahzaibWaseem** [hzxie/Pix2Vox#6]
![image](https://user-images.githubusercontent.com/22326961/63265581-3dd49f80-c28e-11e9-999e-b1d1f5887a54.png)
I'm getting this issue with the shapes when i run the command *python runner.py --test --weights=Pix2Vox-F-ShapeNet.pth*

**Comment by hzxie** [comment]
Before you load the model of Pix2Vox-F, please checkout to the `Pix2Vox-F` branch with the following command:

```
git checkout -b Pix2Vox-F origin/Pix2Vox-F
```

BTW, please double check your path of 3D volumes. Please edit the following line in `config.py`:

```
__C.DATASETS.SHAPENET.VOXEL_PATH            = '/path/to/Datasets/ShapeNet/ShapeNetVox32/%s/%s/model.binvox'
```
