### ISSUE TITLE
Trainning details on single-view and multi-view

### ISSUE THREAD

**Issue by rokudoyly** [hzxie/Pix2Vox#60]
Greetings,
In your paper,  _First, we train networks except for the multi-scale context-aware fusion using single-view images for 250 epochs. We then train the networks using multi-view images for 100 epochs._    I have two questions about it,

1. Why trainning the network did not directly using multi-view images for 350 epochs or more epochs? 
2. In the config.py, `__C.CONST.N_VIEWS_RENDERING                 = 1 ` Whether the setting control tranning networks using single-view images?  If I want to trainning network using multi-view images, I just need to change the value. For example, I want to trainning network using three-view images, I need to change the code to `__C.CONST.N_VIEWS_RENDERING                 = 3 ` ?

Thank you in advance. @hzxie

**Comment by hzxie** [comment]
1. You need to train the whole network (without the context-aware fusion module) with a single-view image for 250 epochs. Then you need to fix the encoder and decoder and train the rest of the network for 100 epochs to make the network generalize to different numbers of input views.

2. As shown in the following code:

https://github.com/hzxie/Pix2Vox/blob/f1b82823e79d4afeedddfadb3da0940bcf1c536d/core/train.py#L257-L261

`__C.CONST.N_VIEWS_RENDERING = 3` means that the network is trained with a random number of views ranging from 1 to 3. Therefore, you do not need to train the network for each number of views again and again.

**Comment by rokudoyly** [comment]
> 1. You need to train the whole network (without the context-aware fusion module) with a single-view image for 250 epochs. Then you need to fix the encoder and decoder and train the rest of the network for 100 epochs to make the network generalize to different numbers of input views.
> 2. As shown in the following code:
> 
> https://github.com/hzxie/Pix2Vox/blob/f1b82823e79d4afeedddfadb3da0940bcf1c536d/core/train.py#L257-L261
> 
> `__C.CONST.N_VIEWS_RENDERING = 3` means that the network is trained with a random number of views ranging from 1 to 3. Therefore, you do not need to train the network for each number of views again and again.

Thank you for your reply! When train the networks using multi-view images for 100 epochs, how many views did you set at this training state?  For example, 2-views or more.

**Comment by hzxie** [comment]
I think I set this value to 20. 
I can't remember it clearly because it is too far away from now.
