### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by tiexuedanxin** [hzxie/Pix2Vox#61]
hello, I follow your read me  update the config.py, __C.DATASETS.PASCAL3D.ANNOTATION_PATH       = '/path/to/Datasets/PASCAL3D/Annotations/%s_imagenet/%s.mat'
__C.DATASETS.PASCAL3D.RENDERING_PATH        = '/path/to/Datasets/PASCAL3D/Images/%s_imagenet/%s.JPEG'
__C.DATASETS.PASCAL3D.VOXEL_PATH            = '/path/to/Datasets/PASCAL3D/CAD/%s/%02d.binvox'
, but you don't say where to download the PASCAL3D dataset.

**Comment by hzxie** [comment]
https://cvgl.stanford.edu/projects/pascal3d.html

**Comment by tiexuedanxin** [comment]
> https://cvgl.stanford.edu/projects/pascal3d.html

hello, which version of the dataset is you used the PASCAL3D+_release1.0 or 1.1?

**Comment by hzxie** [comment]
Actually, we do not use the PASCAL 3D+ dataset in our paper. Because the training and testing split of the dataset is not correct.
