### ISSUE TITLE
No .binvox files for PASCAL3D!

### ISSUE THREAD

**Issue by tiexuedanxin** [hzxie/Pix2Vox#62]

**Comment by hzxie** [comment]
善意的提醒：请不要做伸手党。谢谢。

**Comment by xujunjiejerry** [comment]
May I ask how this problem can be solved? If the Pascal3D dataset is not used, what can be used as an alternative? Looking forward to your reply.

**Comment by hzxie** [comment]
Please refer to the answers in the following issues.

1. #25
2. #4 
3. #114
