### ISSUE TITLE
How to get the same visualization effect as in the paper？

### ISSUE THREAD

**Issue by XuHHHHH** [hzxie/Pix2Vox#67]
Greetings,
This is the visualization effect I got by using the axes3d package:
![image](https://user-images.githubusercontent.com/50764159/113149811-ff72d500-9265-11eb-8d8a-14954d9d480f.png)
I want to know what software or software package is used in the pix2vox paper to export the visualization file:
![image](https://user-images.githubusercontent.com/50764159/113150094-495bbb00-9266-11eb-8eb0-bb9cdc877848.png)
Thanks.

**Comment by hzxie** [comment]
Please refer to https://github.com/davidstutz/bpy-visualization-utils

**Comment by sujuyu** [comment]
> 问候，
> 这是我通过使用axes3d软件包获得的可视化效果： 我想知道pix2vox论文中使用了哪种软件或软件包来导出可视化文件： 谢谢。
> ![图像](https://user-images.githubusercontent.com/50764159/113149811-ff72d500-9265-11eb-8d8a-14954d9d480f.png)
> 
> ![图像](https://user-images.githubusercontent.com/50764159/113150094-495bbb00-9266-11eb-8eb0-bb9cdc877848.png)

Have you solved the problem?Hope to try your solution.Thank you very much
