### ISSUE TITLE
Could not be broadcast together with shape (1038,) (1037,)

### ISSUE THREAD

**Issue by 5RJ** [hzxie/Pix2Vox#7]
Mr. hzxie, I'm trying to do something with your Pix2Vox work, but there seems to be some problems caused by the version of pytorch, so could you please show me the version you use?

The attach files show the problem with pytorch 1.0
![1](https://user-images.githubusercontent.com/41320257/64915952-d97e0080-d7a5-11e9-8433-a9039a5520b5.png)

**Comment by 5RJ** [comment]
please ignore the name 'pytorch1.2'

**Comment by hzxie** [comment]
I think the problem is not caused by the version of PyTorch but the data of binvox files.

**Comment by 5RJ** [comment]
Thanks for you reply! I'll try to figure it out!


------------------ 原始邮件 ------------------
发件人: "Haozhe Xie"<notifications@github.com>;
发送时间: 2019年9月15日(星期天) 中午11:29
收件人: "hzxie/Pix2Vox"<Pix2Vox@noreply.github.com>;
抄送: "吴芮葭"<986570623@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [hzxie/Pix2Vox] The version of pytorch  (#7)




I think the problem is not caused by the version of PyTorch but the data of binvox files.

**Comment by 5RJ** [comment]
The problem is caused by the inconsistency between value and counts.We can print the shape to get it.
