### ISSUE TITLE
What is the meaning of "Baseline" in the test results?

### ISSUE THREAD

**Issue by sujuyu** [hzxie/Pix2Vox#70]
I'm sorry to trouble you again. I want to know the meaning of this dataline in the test process. A little help from you would be greatly appreciated
![image](https://user-images.githubusercontent.com/58780297/114650486-eada1680-9d14-11eb-9868-4a43125e7937.png)
Thank you very much.

**Comment by hzxie** [comment]
"Baseline" is the IoU of 3D-R2N2. Because we take 3D-R2N2 as our baseline.

**Comment by ikhblo** [comment]
Hello, I want to ask what does t=0.20  t=0.30 t=0.40 t=0.50 mean.Thank you very much.

**Comment by sujuyu** [comment]
> Hello, I want to ask what does t=0.20 t=0.30 t=0.40 t=0.50 mean.Thank you very much.

It means the voxelization threshold. For example, if a floating-point number in the output matrix is 0.35 (representing the voxel probability), this position is not occupied at t = 0.4, but is occupied if t = 0.3 is selected. The final result only has 0 indicating unused and 1 indicating occupied, but the output matrix is a floating point number representing probability, so t is required to do binarization processing. Generally, t = 0.3 or t = 0.4 is the best choice

**Comment by ikhblo** [comment]
I get it, thanks a lot for your reply.
