### ISSUE TITLE
One question on F-Score

### ISSUE THREAD

**Issue by rokudoyly** [hzxie/Pix2Vox#76]
Greetings,
In your paper,  there are two evaluation metrics, Iou and F-Score. But there is not including F-Score in your test [code.](https://github.com/hzxie/Pix2Vox/blob/master/core/test.py) Could you provide some details about realizing F-Score in the test code? Thank you in advance.

**Comment by faridyagubbayli** [comment]
Hi, I don't know the exact code used to report the results but in the Pix2Vox++ paper, a reference to [this work](https://lmb.informatik.uni-freiburg.de/Publications/2019/TB19/paper-s3d.pdf) was given when talking about F-score. [The code](https://github.com/lmb-freiburg/what3d) for the referenced paper includes the F-score calculation.

**Comment by rokudoyly** [comment]
> Hi, I don't know the exact code used to report the results but in the Pix2Vox++ paper, a reference to [this work](https://lmb.informatik.uni-freiburg.de/Publications/2019/TB19/paper-s3d.pdf) was given when talking about F-score. [The code](https://github.com/lmb-freiburg/what3d) for the referenced paper includes the F-score calculation.

Thanks for your help！I solved.

**Comment by mengliang321** [comment]
> > Hi, I don't know the exact code used to report the results but in the Pix2Vox++ paper, a reference to [this work](https://lmb.informatik.uni-freiburg.de/Publications/2019/TB19/paper-s3d.pdf) was given when talking about F-score. [The code](https://github.com/lmb-freiburg/what3d) for the referenced paper includes the F-score calculation.
> 
> Thanks for your help！I solved.

Hi, Could you provide some details about realizing F-Score in the test code? Thank you in advance.

**Comment by rokudoyly** [comment]
> > > Hi, I don't know the exact code used to report the results but in the Pix2Vox++ paper, a reference to [this work](https://lmb.informatik.uni-freiburg.de/Publications/2019/TB19/paper-s3d.pdf) was given when talking about F-score. [The code](https://github.com/lmb-freiburg/what3d) for the referenced paper includes the F-score calculation.
> > 
> > 
> > Thanks for your help！I solved.
> 
> Hi, Could you provide some details about realizing F-Score in the test code? Thank you in advance.

You can refer to this link [https://github.com/lmb-freiburg/what3d](url) and the issue [https://github.com/lmb-freiburg/what3d/issues/1](url).

**Comment by Meng-111** [comment]
> > Hi, Could you provide some details about realizing F-Score in the test code? Thank you in advance.
> 
> You can refer to this link [https://github.com/lmb-freiburg/what3d](url) and the issue [https://github.com/lmb-freiburg/what3d/issues/1](url).
Thank you for your reply ! In fact, I have tried that, but failed, so I want to know how you solved it

**Comment by rokudoyly** [comment]
> > > Hi, Could you provide some details about realizing F-Score in the test code? Thank you in advance.
> > 
> > 
> > You can refer to this link [https://github.com/lmb-freiburg/what3d](url) and the issue [https://github.com/lmb-freiburg/what3d/issues/1](url).
> > Thank you for your reply ! In fact, I have tried that, but failed, so I want to know how you solved it

Could you show me about the difficulties which you met?

**Comment by Meng-111** [comment]
> > > > Hi, Could you provide some details about realizing F-Score in the test code? Thank you in advance.
> > > 
> > > 
> > > You can refer to this link [https://github.com/lmb-freiburg/what3d](url) and the issue [https://github.com/lmb-freiburg/what3d/issues/1](url).
> > > Thank you for your reply ! In fact, I have tried that, but failed, so I want to know how you solved it
> 
> Could you show me about the difficulties which you met?

Thanks for your help ! I solved.

**Comment by YYTYTY** [comment]
I'm sorry to trouble you again. I want to know the results of f-score in the test process.  I can't get the accuracy as the Pix2Vox++. A little help from you would be greatly appreciated!

![1](https://user-images.githubusercontent.com/59073666/124353759-f31e5f80-dc3a-11eb-9f63-01342262a472.png)

**Comment by rokudoyly** [comment]
> I'm sorry to trouble you again. I want to know the results of f-score in the test process. I can't get the accuracy as the Pix2Vox++. A little help from you would be greatly appreciated!
> 
> ![1](https://user-images.githubusercontent.com/59073666/124353759-f31e5f80-dc3a-11eb-9f63-01342262a472.png)

Actually, we also get the wrong result. We test the single-view result and the value is 0.449. We still do not find out the reason. Besides. we find that the sampling is calculated by CPU which will waste too much time, do you also meet this trouble?

**Comment by YYTYTY** [comment]
> > I'm sorry to trouble you again. I want to know the results of f-score in the test process. I can't get the accuracy as the Pix2Vox++. A little help from you would be greatly appreciated!
> > ![1](https://user-images.githubusercontent.com/59073666/124353759-f31e5f80-dc3a-11eb-9f63-01342262a472.png)
> 
> Actually, we also get the wrong result. We test the single-view result and the value is 0.449. We still do not find out the reason. Besides. we find that the sampling is calculated by CPU which will waste too much time, do you also meet this trouble?

Yes.  Because Numpy cannot read CUDA tensor and needs to convert it to CPU tensor.

**Comment by Tcode8** [comment]
> > > 很抱歉再次给您添麻烦了。我想知道测试过程中的 f-score 结果。我无法获得像 Pix2Vox++ 那样的准确率。如果您能提供一点帮助，我将不胜感激！
> > > ![1](https://user-images.githubusercontent.com/59073666/124353759-f31e5f80-dc3a-11eb-9f63-01342262a472.png)
> > 
> > 
> > 其实，我们也得到了错误的结果，我们测试了单视图的结果，结果是0.449，但还是没找到原因，另外我们发现采样是用CPU计算的，会浪费太多时间，你们也遇到过这个问题吗？
> 
> 是的。因为 Numpy 无法读取 CUDA 张量，需要将其转换为 CPU 张量。

Hey! May I ask how your F1 score is calculated? Can you please show me your test code
