### ISSUE TITLE
Availability of ShapeNet-Chairs-RfC dataset or pretrained Pix2Vox++ models on ShapeNet-Chairs-RfC dataset

### ISSUE THREAD

**Issue by Sirish07** [hzxie/Pix2Vox#78]
Hello @hzxie sir,

I am trying to reproduce Pix2Vox++ results on Pix3D dataset, however, I am not able to find either the ShapeNet-Chairs-RfC dataset or any pretrained Pix2Vox++ models available. Is it possible to release any of them ? Thank you for your time and consideration.

Regards,
Sirish Gambhira.

**Comment by hzxie** [comment]
There is no plan to release the two datasets.
