### ISSUE TITLE
Process shutting down problem

### ISSUE THREAD

**Issue by BAn21** [hzxie/Pix2Vox#8]
![KakaoTalk_20190922_200023457](https://user-images.githubusercontent.com/22498708/65387739-2b65ee00-dd85-11e9-943e-584bf7248a69.jpg)
hello, This is my problem.
At first I thought about the TensorBoard version problem, but the TensorBoard is using 1.8.
can you help me..?

**Comment by hzxie** [comment]
Please downgrade the TensorBoardX to 1.2.0

**Comment by BAn21** [comment]
wow.. it was really version problem. now, epoch 2!
Thanks.
