### ISSUE TITLE
“memory” in your paper, what does it mean and how to compute it?

### ISSUE THREAD

**Issue by bizbard** [hzxie/Pix2Vox#81]
Would you please explain the "Memory(MB)" of Table 4 in your paper(Pix2Vox: Context-aware 3D Reconstruction from Single and Multi-view Images)? And how do you compute it?

**Comment by hzxie** [comment]
Sorry for the late reply.

1. The memory in Table 4 is for single-view 3D reconstruction.
2. The values come from `nvidia-smi`.
