### ISSUE TITLE
How to get the same visualization of the score maps as in the paper?

### ISSUE THREAD

**Issue by chirsyes** [hzxie/Pix2Vox#82]
Greetings, I like the visualization of the score maps in Figure 4, could you tell me how to generate the same score maps? Is there any code or reference?
![微信图片_20220207081937](https://user-images.githubusercontent.com/99055680/152708403-4648f947-0995-4112-a206-08713cb69710.png)

**Comment by hzxie** [comment]
Just use matplotlib.
I don't save that code.
