### ISSUE TITLE
Training on Custom Dataset

### ISSUE THREAD

**Issue by mahnoor-fatima-saad** [hzxie/Pix2Vox#83]
Hi 

Absolutely amazing work. I was doing some research and I would like to create a custom dataset like the test set for Pix3d. Can you please provide some guidance on how I should go about that? What would be the structure of the dataset and how did you create your own so that I can follow similar steps to create my dataset for my use case. 

Thanks in advance.

**Comment by hzxie** [comment]
You need to modify the data loaders defined in https://github.com/hzxie/Pix2Vox/blob/master/utils/data_loaders.py
