### ISSUE TITLE
Custom dataset training with ShapeNet-like structure.

### ISSUE THREAD

**Issue by sobikim** [hzxie/Pix2Vox#88]
Hi.
I have some questions for training using custom dataset(ShapeNet-like structure)

1. If not 24 images per object, would it be a problem for training?
2. If the image size isn't 137 x 137, would it be a problem for training?
3. If the object isn't centered in the image, will it be a problem for training?

Thank you!

**Comment by hzxie** [comment]
1. No
2. No
3. No

**Comment by sobikim** [comment]
Thank you very much!
