### ISSUE TITLE
voxel size 

### ISSUE THREAD

**Issue by kaphleamrit2** [hzxie/Pix2Vox#89]
I am trying to train my custom data. Voxel size of all of my binvox files are 256x256x256. I got the following errors:

`ValueError: Using a target size (torch.Size([1, 256, 256, 256])) that is different to the input size (torch.Size([1, 32, 32, 32])) is deprecated. Please ensure they have the same size.`

How can I train with 256 voxel size?

**Comment by hzxie** [comment]
You need to update the network architecture.

**Comment by hzxie** [comment]
I'm not sure whether the GPU memory is enough to generate 256^3 voxels.

**Comment by kaphleamrit2** [comment]
Thanks for the reply @hzxie . Any idea in which network and where architecture I need to update if I want to use higher voxel?

**Comment by zhd633** [comment]
> Thanks for the reply @hzxie . Any idea in which network and where architecture I need to update if I want to use higher voxel?

Thanks, I have the same question，did you solve this problem?
