### ISSUE TITLE
ShapeNetRendering metadata introduction

### ISSUE THREAD

**Issue by 5RJ** [hzxie/Pix2Vox#9]
Hello, Mr. hzxie. Thanks for the shapenet dataset link you provided.In 
 ShapeNetRendering, each sample contains a rendering_metadata.txt, but after searching online,  I only found such a profile (''From the left, they are azimuth, elevation, in-plane rotation, distance, the field of view.''). I am still confused about the 'distance', could you please show me the specific meaning? And if it's convenient, could you please also put on the specific metadata introduction ? I will be grateful for everything you have done.

**Comment by hzxie** [comment]
Please refer to: https://github.com/chrischoy/3D-R2N2/issues/12

**Comment by hzxie** [comment]
Please consider reading papers on 6D Pose Estimation.
If you need a very accurate pose, please generate it during rendering.

**Comment by gaetan-landreau** [comment]
This issue shouldn't be closed since the provided answer: 

> Please refer to: [chrischoy/3D-R2N2#12](https://github.com/chrischoy/3D-R2N2/issues/12)

is already mentioned as unsatisfying regarding the distance parameter in the issue question.
