### ISSUE TITLE
training result questions

### ISSUE THREAD

**Issue by sobikim** [hzxie/Pix2Vox#91]
Hi.

I have some questions about training results.

1. In the figure below, does "t=0.20" mean the threshold for binarization of voxels?
![image](https://user-images.githubusercontent.com/86090720/180146036-1c055cd1-4001-4a4f-a5f7-9d87abf27858.png)

2. When training, there are a lot of images in the "./output/images/time/test" folder. What are these images? It doesn't look like a prediction, is it the ground truth?

Thank you!

**Comment by hzxie** [comment]
1. Yes
2. `./output` is in the `.gitignore`. If there are files in the `./output` folder, they must be generated by yourself.

**Comment by sobikim** [comment]
Maybe I didn't ask clearly.

When I train Pix2Vox, a lot of images of voxels are created in that folder("./output/images/2022-06-30T04:43:11.767915/test").
![voxels-000001](https://user-images.githubusercontent.com/86090720/180339096-31225a77-ab22-4466-b632-c87d2b37a714.png)
Is this a predicted voxel? or ground truth voxel?

Thank you!

**Comment by hzxie** [comment]
The images are generated with the following code.

https://github.com/hzxie/Pix2Vox/blob/f1b82823e79d4afeedddfadb3da0940bcf1c536d/core/test.py#L150-L155

Some of them are GT, and the rest are predictions.

**Comment by sobikim** [comment]
I understand.
Thank you always!!
