### ISSUE TITLE
Testing with pix3d dataset

### ISSUE THREAD

**Issue by xphn** [hzxie/Pix2Vox#92]
Hi thank you so much for the great work. I am having some difficulties in implementing your work during testing on the pix3d dataset. In the instruction, it is mentioned that we need to define the link to the binvox files. However, there is no binvox file that comes with pix3d dataset. The following is the change I made in the config file

__C.DATASETS.PIX3D.VOXEL_PATH = 'C:/Users/peng/Desktop/pix2vox/datasets/pix3d/model/%s/%s/%s.binvox'

Thank you very much

**Comment by hzxie** [comment]
You can generate voxels from the provided mesh models.
