### ISSUE TITLE
The extrinsic and intrinsic of camera in the ShapeNetrendering

### ISSUE THREAD

**Issue by Sand-Glass** [hzxie/Pix2Vox#95]

**Comment by Sand-Glass** [comment]
![image](https://user-images.githubusercontent.com/96899552/201504878-3af03704-ce76-43a3-9373-e1e1e16d3577.png)
I want to know the meaning of all parameters in the rendering_metadata.txt
And how can I construct the like above?
![image](https://user-images.githubusercontent.com/96899552/201504887-d270d584-dd73-4671-ae03-a56981763353.png)

**Comment by hzxie** [comment]
Please refer to #9
